### ISSUE TITLE
Production Ready PostgreSQL

### ISSUE THREAD

**Issue by jmealo** [JarvusInnovations/lapidus#1]
- [ ] Write test(s) to verify that spawned [pg_recvlogical](http://www.postgresql.org/docs/9.5/static/app-pgrecvlogical.html) processes die immediately if Node exits.
- [x] <s>Find way to get the [LSN](http://www.postgresql.org/docs/9.5/static/datatype-pg-lsn.html) for each event (this will have to happen in the logical decoding plugin)</s>
- [x] <s>After each event write the latest [LSN](http://www.postgresql.org/docs/9.5/static/datatype-pg-lsn.html) to file in such a way that a partial write will allow Lapidus to start at the last known good position.</s>
- [x] <s>When configured, Lapidus should gracefully read the last known [LSN](http://www.postgresql.org/docs/9.5/static/datatype-pg-lsn.html) from file and use that as the starting position when spawning [pg_recvlogical](http://www.postgresql.org/docs/9.5/static/app-pgrecvlogical.html)</s>
- [x] If [pg_recvlogical](http://www.postgresql.org/docs/9.5/static/app-pgrecvlogical.html) dies, Node should respawn it
- [ ] Write tests for connection related error handling and events
- [x] Write test suite for logical decoding plugins to verify all built-in data types work as expected; this should be plugin agnostic and be architected in such a way that it can be used to compare multiple plugins for accuracy/performance comparison and regression tests.

**Comment by jmealo** [comment]
@leptonix is it hard to add an option to include the LSN?

I'm not entirely sure if this is needed yet, I believe that `pg_recvlogical` should be incrementing the last read LSN for the slot it's connected to, but to prevent any repeat events it seems safer for Lapidus to keep track as well.

**Comment by ruslantalpa** [comment]
@jmealo Would it be possible to add the following features to PostgreSQL support:
- The pg role that executed the UPDATE/DELET/INSERT
- Events generated by NOTIFY
- Env variables values at the tame of the query (i know this is far fetched :) ).

Usecase is this:
This project would probably be used to implement "live update" feature in projects and in cases like that it's useful to know who generated the event in order to make a decision who will be the recipients of that event.
In a PostgREST setup, that info would come from the pg role and the env variables like `postgrest.claims`
For cases when the things are a bit more complex then an insert/update/delete, like a stored procedure, a user can have the option to use NOTIFY to create a custom event.

**Comment by jmealo** [comment]
@ruslantalpa Sorry for the slow response, I need to tweak my Gmail filters and will make an effort to respond within 24 hours in the future.

Lapidus only has access to what is written to the database, if you don't write it, we don't have it. To avoid feature bloat or inadvertently becoming a message broker, I'd like to limit Lapidus to streaming changes as they are written to the database.

Lapidus uses streaming replication or its equivalent, which don't provide the role who issued an SQL query. You can do this using a trigger or through query logging. (Yes, you could have PostgreSQL log the entire query. If you want your application to pass along any information, like the current logged in user, you can set the GUC `application_name` variable at the beginning of your query. Then simply include the application_name in your log format and viola).
1. Do you really care about the database role or are you interested in the application user? There's not a good way to do this in the database without doubling or tripling your write load and adding triggers all over the place or abusing logging facilities. It's possible that at some point you could do it at the protocol level if you use connection pooling but that'd be an entirely different beast. If you go the audit logging trigger route these events will be emitted in Lapidus just like any other event.
2. You'd like Lapidus to `listen` to `notify` events? Right now we don't connect directly to PostgreSQL, we use the replication protocol through a command line tool bundled with PostgreSQL. As I add features that may need introspection into the database, I may need to connect as a normal client (in which case I could `listen` for events).

You can include lapidus as a module and add `listen` for `notify` events in less than 20 lines of code; here's a somewhat dated example:
http://bjorngylling.com/2011-04-13/postgres-listen-notify-with-node-js.html

If we add this feature, it seems like Lapidus would become an event or message broker which I'm interested in spinning off as a separate project that works with Lapidus.

@begriffs: Perhaps you could expose an option in the configuration for PostgREST to abuse the `application_name` GUC to allow for advanced logging using PostgreSQL's built-in logging.

**Comment by begriffs** [comment]
@jmealo cool I didn't know you can set the application name in the logs. [This article](https://stackoverflow.com/questions/15685861/setting-application-name-on-postgres-sqlalchemy) suggests that you can pass it in the connection string as an argument. Have you tried modifying the connection string command line option when starting PostgREST?

**Comment by ruslantalpa** [comment]
I guess the simplest solution would be to create a stored procedure that issues a "notify" with a standardised message body and whenever you are interested in events on that table, you add that function as a trigger to that table, and on the other end you listen using nodejs of anything else.

Is there a notion of queue in postgres so that multiple clients can subscribe to that queue and process messages in paralel?
I guess the nodejs part could act only as a proxy to a full messaging system (which implements the queue) but it would be a bit would be choke node in the chain since only one process can act as a proxy at a time

**Comment by jmealo** [comment]
@begriffs I set the application_name for everything that connects to my database so that my pg_badger reports are more meaningful.

I edited the PostGREST init.d script to read as follows:

``` shell
CONNECTION_STRING="$CONNECTION_STRING@$POSTGREST_DBHOST:$POSTGREST_DBPORT/$POSTGREST_DBNAME?application_name=postgrest"
```

I believe that it took effect.

@ruslantalpa I don't like the overhead of a trigger or listen/notify that's why I created Lapidus, there's no reason for triggers if you only want to stream changes from the database, there's facilities in PostgreSQL and MySQL to do just that. It sounds like what you really want is audit logging, in which case you can add a trigger to do that, and can even include a column on each table `last_modified_by` and store the web application user or database role that made the change. This column would be included in the Lapidus event.
